### PR TITLE
Use Non-OGP template if any of required OG tags are missing from the page

### LINKED ISSUE #37: Pages with meta tags, all of whose property attr are unrelated to OG properties ruins the preview
## The issue

I attempted to `linkpreview` the following URL:
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.InputSystem.html
It is a documentation page for Unity's package.

### Expected behavior

This link does not appear to have any OGP properties, so I expected this plugin to produce a "no OGP image link preview snippet" with the title `Class InputSystem | Input System | 1.0.2`.

### Actual behavior

This happened.

[Image from Gyazo](https://gyazo.com/468e2a184c57bb44423300f9b7f3a754)

* Jekyll-linkpreview attempted to render the "link preview with OGP image snippet" (`linkpreview.html`) even though there are no OG properties on this page
* The title, description, and image are missing (missing image is expected, but the other two are not.)

I looked into the cache and found that the corresponding file had this:

```json
{"title":null,"url":null,"image":null,"description":null,"domain":"docs.unity3d.com"}
```
(filename: cec2702fa0dbc6125ac754817ddbb10b.json)

## Suspected issues

This page has these `<meta>` tags in its HTML:

```html
    <meta property="docfx:navrel" content="../toc.html">
    <meta property="docfx:tocrel" content="toc.html">
    <meta property="unity:packageTitle" content="Input System | 1.0.2">
    <meta property="docfx:rel" content="../">
```

So this page has `<meta>` tags with a `property` attribute, but its value is never `og:.*`. This edge case of an HTML page causes this method to miss this case and causes it to spawn `OpenGraphPropertiesFactory` when it should be spawning `NonOpenGraphPropertiesFactory` instead.

https://github.com/ysk24ok/jekyll-linkpreview/blob/61c8b0b1e8f5f004c6df1248f9f0d71577a01bfe/lib/jekyll-linkpreview.rb#L190-L198

(Any `<meta>` tag whose property attribute value matches `og:.*` on this page and the plugin would have avoided this issue.)

## Potential fix

In addition to `page.meta_tags['property'].empty?`, check for the total absence of `property` attributes whose value matches regex `og:.*`. If any of those holds, we should use `NonOpenGraphPropertiesFactory`.

### PR DESCRIPTION
**Pull request by Clpsplug**
Closes #37.

This patch modifies the behavior of `create_properties_from_page` so that if the page lacks any of the required OGP tags, it will use a Non-OGP template. This patch prevents users from getting a blank link preview when all the previewed page's meta tags are unrelated to OGP.

Disregard the part below, I found a way to test this patch :)
~~There are currently no tests because I'm struggling to develop a way to test this behavior. Scraping is mocked away in the existing test suits, so adding a test for this patch to any of the existing test suits did not make much sense. `get_properties` includes fetching the page and extracting the properties, but should we split this method up just so that we can test this patch?~~

### CODE REVIEW

**Comment by Clpsplug** [comment]
Thanks @ysk24ok for #43 hot-fixing the CI! I'll look into this patch as to why the test is crashing now

**Comment by Clpsplug** [comment]
Caught the culprit: an example was missing a required OGP tag `og:type`. I added it to the test.  
That being said, @ysk24ok, I want to discuss whether should `og:type` be accessible by the template and be cached or not. By that, I mean that in `lib/jekyll-linkpreview.rb`, I'd do something along the line of:

```diff
     class OpenGraphProperties
       @@template_file = 'linkpreview.html'

-      def initialize(title, url, image, description, domain)
+      def initialize(title, type, url, image, description, domain)
         @title = title
+        @type = type
         @url = url
         @image = image
         @description = description
```

...and include the `@type` in the hash. I cannot think of any use cases, though, as this value apparently can be anything. So this is just an idea that can be disregarded.

I also found a way to include the OGP/NOGP distinction in the Rake tests, so please take a look.

**Comment by ysk24ok** [comment]
> I want to discuss whether should og:type be accessible by the template and be cached or not

Yes I think basically all properties should be accessible from a template and a cache file.
Please add `link_type` to https://github.com/ysk24ok/jekyll-linkpreview#template-for-pages-where-open-graph-protocol-metadata-exists.
You don't need to add the type variable to the default template.

**Comment by Clpsplug** [comment]
Added as requested! The user should now be able to extract the `og:type` property via `link_type` variable.

I also realized that existing users will not get the `og:type` variable until they bust their caches. The plugin doesn't appear to crash, but a small migration guide may help.

**Review by ysk24ok — APPROVED** [review]

**Pull request merged**
